<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

<div class="contact-div">
    <div class="wrapper">
        <div class="div-block-29">
            <div class="div-block-32">
                <div class="div-block-33">
                    <h1 class="heading-7">Contact Us</h1>
                    <div class="text-block-7">Contact us or submit your enquiries here and we will get back to you as soon as possible.<br>‍</div>
                    <div class="div-block-34"><img src="images/perm_phone_msg_24px.svg" loading="lazy" width="18" alt="" class="image-6">
                        <a href="tel:0702060100" class="link-5">070-2060100</a>
                    </div>
                    <div><img src="images/alternate_email_24px.svg" loading="lazy" width="18" alt="" class="image-6">
                        <a href="mailto:info@krm.nl?subject=Enquiries" class="link-5">info@krm.nl</a>
                    </div>
                </div>
            </div>
            <div class="div-block-30 mobile-view">
                <div class="div-block-36">
                    <h1 class="heading-10">Contact Us</h1>
                    <div class="text-block-8">Contact us or submit your enquiries here and we will get back to you as soon as possible.<br></div>
                    <div class="div-block-34"><img src="images/perm_phone_msg_24px.svg" loading="lazy" width="18" alt="" class="image-6">
                        <a href="tel:0702060100" class="link-5">070-2060100</a>
                    </div>
                    <div class="div-block-38"><img src="images/alternate_email_24px.svg" loading="lazy" width="18" alt="" class="image-6">
                        <a href="mailto:info@krm.nl?subject=Enquiries" class="link-5">info@krm.nl</a>
                    </div>
                    <div class="div-block-38"><img src="images/location_on_24px.svg" loading="lazy" width="18" alt="" class="image-6">
                        <div>
                            <div class="text-block-9">KRM BV<br>Marineweg 3a 2241 TX Wassenaar</div>
                        </div>
                    </div>
                </div>
                <div class="div-block-31">
                    <h4 class="heading-9">Send us a Message</h4>
                    <div class="div-block-35">
                        <div class="form-block login w-form">
                            <form id="email-form" name="email-form" data-name="Email Form" class="form"  method="post">
                                <div class="logindiv contactdiv">
                                    <input type="text" class="text-field login-texfield contact w-input" maxlength="256" name="contact-name" data-name="contact-name" placeholder="Name*" id="contact-name" required="">
                                    <input type="tel" class="text-field login-texfield contact w-input" maxlength="256" name="contact-phone" data-name="contact-phone" placeholder="Phone Number*" id="contact-phone" required="">
                                    <input type="email" class="text-field login-texfield contact w-input" maxlength="256" name="contact-email" data-name="contact-email" placeholder="Email*" id="contact-email" required="">
                                    <input type="text" class="text-field login-texfield contact w-input" maxlength="256" name="contact-subject" data-name="contact-subject" placeholder="Subject*" id="contact-subject" required="">
                                    <input type="text" class="text-field login-texfield contact w-input" maxlength="256" name="contact-topic" data-name="contact-topic" placeholder="Topic*" id="contact-topic" required="">
                                    <textarea placeholder="Message*" maxlength="5000" id="contact-message" name="contact-message" data-name="contact-message" class="textarea w-input"></textarea></div>
                                <input type="submit" value="Submit" name="submit" data-wait="Please wait..." class="submit-button ghost-btn contact-submit w-button">
                                <div>
                                   <!-- <div class="text-block">Oops! Something went wrong!</div>-->
                                </div>
                            </form>
                            <div class="w-form-done">
                                <div>You Logged In</div>
                            </div>
                            <div class="w-form-fail">
                                <div>Oops! Something went wrong while submitting the form.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

<?php require('template/footer.phtml') ?>
