<!--A header of the website which will be posted on each page of the website.-->

<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>

<!--  from here the main body starts which includes the form of application and will be shown to the user on the website.
 it will also include some div class, sections, headers, paragraphs and some input types in order to create a form and
  add sections which will be used to separate things from form to headings. An example of that is div class used for headings
    and for paragraphs another div is used to add inputs types related to the form.
-->
    <body class="body">

    <div class="form-container">

        <div class="section">
            <h1 class="heading">Project Application</h1>
            <p class="paragraph">Please fill up the form with required information.</p>
            <?php echo '<div class="error-message" id="form-message">'.$view->message.'</div>';?>
            <div class="form-block w-form">
                <form id="email-form" name="email-form" data-name="Email Form" method="post" class="form">
                    <input type="text" class="text-field w-input" maxlength="256" name="project-name"  placeholder="Project Name" id="project-name" required="">
                    <input type="text" class="text-field w-input" maxlength="256" name="short-description"  placeholder="Short Description" id="short-description" required="">
                    <div class="budget-field">
                        <input type="number" class="text-field left-budget-field w-input" maxlength="256" name="min-budget-range"  placeholder="Minimum Budget" id="min-budget-range" required="">
                        <input type="number" class="text-field w-input" maxlength="256" name="max-budget-range"  placeholder="Maximum Budget" id="max-budget-range" required=""></div>
                    <input type="date" class="text-field w-input" maxlength="256" name="deadline" placeholder="Deadline (YYYY-MM-DD)" id="deadline" required="">
                    <input type="text" class="text-field w-input" maxlength="256" name="other-requirement" placeholder="Other Requirements (Optional)" id="other-requirement">

<!--this is an if statement which will check the status of the user being logged in or not using php session.-->
                    <?php

                    if(isset($_SESSION["loggedin"]))
                    {

                    }

                    else{
                        echo'
                        <input type="text" class="text-field w-input" maxlength="256" name="customer-name" placeholder="Customer Name" id="customer-name" required="">
                        <input type="email" class="text-field w-input" maxlength="256" name="email"  placeholder="Email" id="email" required="">
                        <input type="tel" class="text-field w-input" maxlength="256" name="number" placeholder="Phone Number" id="phone-number" required="">
                                <input type="text" class="text-field w-input" maxlength="256" name="address1"  placeholder="Address Line 1" id="address-2" required="">
                                <input type="text" class="text-field w-input" maxlength="256" name="address2"  placeholder="Address Line 2" id="address-3" required="">
                                <input type="text" class="text-field w-input" maxlength="256" name="postcode"  placeholder="Post/Zipcode" id="postcode" required="">
                        ';
                    }



                    ?>
<!-- button to submit the form.-->
                    <input type="submit" value="Submit" name="submit" data-wait="Please wait..." class="submit-button form-submit-btn w-button">

<!-- another form which will be activated after user clicking on the submit button.-->
                </form>
<!-- if everything goes alright then this message will show-->
                <div class="w-form-done">
                    <div>Thank you! Your submission has been received!</div>
                </div>
<!-- opposite message will be shown to the user if something missing or not right on the form.-->
                <div class="w-form-fail">
                    <div>Oops! Something went wrong while submitting the form.</div>
                </div>
            </div>
        </div>
    </div>


<!-- a footer for a website taken from the footer.phtml page of the project-->
<?php require('template/footer.phtml') ?>
