<?php require('template/header.phtml') ?>

<h1>This page is currently under construction</h1>

<body class="body-4">



<div class="history-section">
    <div class="history-block">
        <h1 class="heading-3">Projects History</h1>
        <?php
        if(isset($_SESSION["loggedin"]))
        {
            echo '
                    <div class="text-block-2">You can see your history of projects here.</div>
                </div>
                <div class="div-block-14">
                    <div class="columns w-row">
                        <div class="w-col w-col-4">
                            <h5>Project name:</h5>
                            <div class="text-block-3">project name here</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Project ID:</h5>
                            <div>project id here</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Description:</h5>
                            <p>description here</p>
                        </div>
                    </div>';
        }

        else{
            echo '
                    <div class="text-block-2">Please sign in to view your project application history.</div>
                </div>';
        }
        ?>

    </div>
</div>

<?php require('template/footer.phtml') ?>
