<!--A header of the website which will be posted on each page of the website.-->

<?php require('template/header.phtml') ?>

<!--History page is where user can access all his applications which he submitted to the KRM.-->

<body class="body-4">

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

<div class="history-section">
    <div class="history-block">
        <h1 class="heading-3">Projects History</h1>

<!-- an if statement to check if user has logged in and if yes then he will be able to see the application history.-->

        <?php
        if(isset($_SESSION["loggedin"]))
        {
            $count=1;
            echo'<div class="text-block-2">You can see your history of projects here.</div>
                </div>
                <form>
                
<!-- a button to bring all the applications in alphabetical order-->

                    <input type="submit" name="order" value="Order A-Z" data-wait="Please wait..." class="submit-button-2 uf-mobile-view w-button">
                </form>
                <div class="card-wrapper mobile-view-card-wrapper">';


//  foreach loop here is used to bring so everytime it executes it brings all this data from the application data table.

            foreach ($view->applicationData as $appData) {
                echo '
                    
                <!--<div class="div-block-14">
                <h1 class="heading-3">Application '.$count.'</h1>
                    <div class="columns w-row">
                    
                        <div class="w-col w-col-4">
                            <h5>Application ID:</h5>
                            <div class="text-block-3">'.$appData->getApplicationID().'</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Project name:</h5>
                            <div class="text-block-3">'.$appData->getProjectName().'</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Project Description:</h5>
                            <div>'.$appData->getDescription().'</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Budget Range:</h5>
                            <p>£'.$appData->getMinRange().' to £ '.$appData->getMaxRange().'</p>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Deadline:</h5>
                            <div>'.$appData->getDeadline().'</div>
                        </div>
                        <div class="w-col w-col-4">
                            <h5>Other Requirements:</h5>
                            <div>'.$appData->getOtherReq().'</div>
                        </div>
                    </div>
                    </div>-->
                    
                    
                    
<!-- Application will be shown to the user here using columns each column will have following data and it will be
 collected from application data database-->    
                  
            <div class="project-cards">
                <div class="card-div">
                    <div class="div-block-20"><img src="images/folder_open_24px.svg" loading="lazy" alt=""></div>
                    <div class="div-block-21">
                        <div class="div-block-22">
                            <div class="div-block-23">
                                <div class="div-block-26"><img src="images/Name_.svg" loading="lazy" alt="" class="image-5"></div>
                                <div>
                                    <div class="text-block-6">'.$appData->getProjectName().'</div>
                                </div>
                            </div>
                        </div>
                        <div class="div-block-24">
                            <div class="div-block-25"><img src="images/ID_.svg" loading="lazy" alt=""></div>
                            <div>
                                <div class="text-block-6">'.$appData->getApplicationID().'</div>
                            </div>
                        </div>
                        <div>
                            <div class="div-block-27">
                                <div class="div-block-28"><img src="images/Description_.svg" loading="lazy" alt=""></div>
                                <div>
                                    <div class="text-block-6">'.$appData->getDescription().'<br>‍</div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="div-block-27">
                                <div class="div-block-28"><img src="images/Budget_.svg" loading="lazy" alt=""></div>
                                <div>
                                    <div class="text-block-6">£'.$appData->getMinRange().' to £ '.$appData->getMaxRange().'<br>‍</div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="div-block-27">
                                <div class="div-block-28"><img src="images/Deadline_.svg" loading="lazy" alt=""></div>
                                <div>
                                    <div class="text-block-6">'.$appData->getDeadline().'<br>‍</div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="div-block-27">
                                <div class="div-block-28"><img src="images/Description_.svg" loading="lazy" alt=""></div>
                                <div>
                                    <div class="text-block-6">'.$appData->getOtherReq().'<br>‍</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            
            ';
                $count = $count +1;
            }

        }

// if user is not logged in then this will be shown to the user so he can log in and see his history.

        else{
            echo '
                    <div class="text-block-2">Please <a href="login.php">sign in</a> to view your project application history.</div>
                    <div class="matthew-class"></div>
                </div>';
        }

?>

    </div>


<!--    <div class="history-section">
        <div class="history-block">
            <h1 class="heading-3">Projects History</h1>
            <div class="text-block-2">You can see your history of projects here.</div>
        </div>
        <div class="div-block-14">
            <div class="columns w-row">
                <div class="w-col w-col-4">
                    <h5>Project name:</h5>
                    <div class="text-block-3">project name here</div>
                </div>
                <div class="w-col w-col-4">
                    <h5>Project ID:</h5>
                    <div>project id here</div>
                </div>
                <div class="w-col w-col-4">
                    <h5>Description:</h5>
                    <p>description here</p>
                </div>
            </div>
        </div>
        <div class="card-wrapper mobile-view-card-wrapper">
            <div class="project-cards">
                <div class="card-div">
                    <div class="div-block-20"><img src="images/folder_open_24px.svg" loading="lazy" alt=""></div>
                    <div class="div-block-21">
                        <div class="div-block-22">
                            <div class="div-block-23">
                                <div class="div-block-26"><img src="images/Name_.svg" loading="lazy" alt="" class="image-5"></div>
                                <div>
                                    <div class="text-block-6">Project name to be inserted here</div>
                                </div>
                            </div>
                        </div>
                        <div class="div-block-24">
                            <div class="div-block-25"><img src="images/ID_.svg" loading="lazy" alt=""></div>
                            <div>
                                <div class="text-block-6">Project ID</div>
                            </div>
                        </div>
                        <div>
                            <div class="div-block-27">
                                <div class="div-block-28"><img src="images/Description_.svg" loading="lazy" alt=""></div>
                                <div>
                                    <div class="text-block-6">Project Description<br>‍</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>-->

<!-- a footer for a website taken from the footer.phtml page of the project-->

<?php require('template/footer.phtml') ?>