<?php require('template/header.phtml') ?>

<body>
<div class="home-page">

    <div class="hero-section">
        <div class="hero-section-left-block">
            <h1 class="heading-2">you name it, we build it.</h1>
            <p class="paragraph-2">Active in the secondment of IT specialists for over 20 years. We focus on the nichemarket within ICT. Specialists in the field of infrastructure, security, (software) development and project management.</p>
            <a href="form.html" class="button w-button">Order Your New Application Today</a>
        </div>
        <div class="hero-section-right-block"></div>
    </div>
</div>


<?php require('template/footer.phtml') ?>
