<?php require('template/header.phtml') ?>

<body>
<div class="home-page">

    <div class="hero-section">
        <div class="hero-section-left-block">
            <h1 class="heading-2">you name it, we build it.</h1>
            <p class="paragraph-2">Active in the secondment of IT specialists for over 20 years. We focus on the nichemarket within ICT. Specialists in the field of infrastructure, security, (software) development and project management.</p>
            <a href="form.html" class="button w-button">Order Your New Application Today</a>
        </div>
        <div class="hero-section-right-block"></div>
    </div>
</div>
<script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ffdee642c9118659a48a86b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="js/webflow.js" type="text/javascript"></script>
<!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>

<?php require('template/footer.phtml') ?>
