<!--A header of the website which will be posted on each page of the website.-->

<?php require('template/header.phtml') ?>

<!-- a body tag on the index page which will be shown the user once user load the website.-->
<body>
<div class="home-page">

    <div class="hero-section">

<!-- a section on the right hand side which will include an image to make the website standout. -->
        <div class="hero-section-right-block mobile-view"></div>

        <!-- a section on the left hand side which will include some text headers. -->
        <div class="hero-section-left-block">

            <!-- headers and paragraph. -->
            <h1 class="heading-2">you name it, we build it.</h1>
            <p class="paragraph-2">Active in the secondment of IT specialists for over 20 years. We focus on the nichemarket within ICT. Specialists in the field of infrastructure, security, (software) development and project management.</p>
            <a href="form.php" class="button w-button">Order Your New Application Today</a>
        </div>
        <div class="hero-section-right-block"></div>
    </div>
</div>


<!-- a footer for a website taken from the footer.phtml page of the project-->
<?php require('template/footer.phtml') ?>
