<?php require('template/header.phtml') ?>


<body class="login-body">
  <div data-collapse="none" data-animation="default" data-duration="400" role="banner" class="navbar w-nav">
    <div class="container w-container">
      <nav role="navigation" class="w-nav-menu">

        <a href="register.php" class="nav-link nav-button register-btn w-nav-link">Register</a>
      </nav>
      <div class="w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
      <a href="index.html" class="w-inline-block"><img src="../images/krm..svg" loading="lazy" alt="" class="image"></a>
    </div>
  </div>
  <div class="form-container">
    <div class="section login-section">
      <div class="login-divblock">
        <div class="left-divblock"><img src="../images/login-image.jpg" loading="lazy" srcset="../images/login-image-p-500.jpeg 500w, images/login-image-p-800.jpeg 800w, images/login-image-p-1080.jpeg 1080w, images/login-image-p-1600.jpeg 1600w, images/login-image-p-2000.jpeg 2000w, images/login-image-p-2600.jpeg 2600w, images/login-image-p-3200.jpeg 3200w, images/login-image.jpg 6622w" sizes="(max-width: 767px) 100vw, (max-width: 991px) 46vw, 100vw" alt="" class="image-3"></div>
        <div class="right-divblock">
          <h1 class="heading">Log In</h1>
          <div class="form-block login w-form">
            <form id="email-form" name="email-form" data-name="Email Form" class="form">
              <div class="logindiv"><input type="email" class="text-field login-texfield email-textfield w-input" maxlength="256" name="email" data-name="email" placeholder="Email" id="email-3" required=""><input type="password" class="text-field login-texfield w-input" maxlength="256" name="password" data-name="password" placeholder="Password" id="password" required="">
                <a href="#" class="link-2">Forgot Password?</a>
              </div><input type="submit" value="Log In" data-wait="Please wait..." class="submit-button ghost-btn w-button">
              <div class="register-text-div"><label class="field-label-2">Doesn&#x27;t Have Account? </label>
                <a href="register.phtml" class="register-link-text">Register</a>
              </div>
            </form>
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form.</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-container"><img src="../images/Screenshot-2021-01-13-at-00.21.32.png" loading="lazy" sizes="(max-width: 3360px) 100vw, 3360px" srcset="../images/Screenshot-2021-01-13-at-00.21.32-p-500.png 500w, images/Screenshot-2021-01-13-at-00.21.32-p-800.png 800w, images/Screenshot-2021-01-13-at-00.21.32-p-1080.png 1080w, images/Screenshot-2021-01-13-at-00.21.32-p-1600.png 1600w, images/Screenshot-2021-01-13-at-00.21.32-p-2000.png 2000w, images/Screenshot-2021-01-13-at-00.21.32-p-2600.png 2600w, images/Screenshot-2021-01-13-at-00.21.32-p-3200.png 3200w, images/Screenshot-2021-01-13-at-00.21.32.png 3360w" alt=""></div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ffdee642c9118659a48a86b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="../js/webflow.js" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

<?php require('template/footer.phtml') ?>