<!--A header of the website which will be posted on each page of the website.-->
<?php require('template/header.phtml') ?>

<!-- a form has been used here for the login page where user will be able to log in and see his/her applications
 and also for those users who do not consent to go through this process then they will also be able to
 continue as guest.-->

<!-- a form action within the php tag to secure the website so the user wont be able to see what is hidden in this  -->

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
<!--<body class="login-body">
  <div class="form-container">
    <div class="section login-section">
      <div class="login-divblock">
        <div class="left-divblock"><img src="../images/login-image.jpg" loading="lazy" srcset="../images/login-image-p-500.jpeg 500w, images/login-image-p-800.jpeg 800w, images/login-image-p-1080.jpeg 1080w, images/login-image-p-1600.jpeg 1600w, images/login-image-p-2000.jpeg 2000w, images/login-image-p-2600.jpeg 2600w, images/login-image-p-3200.jpeg 3200w, images/login-image.jpg 6622w" sizes="(max-width: 767px) 100vw, (max-width: 991px) 46vw, 100vw" alt="" class="image-3"></div>
        <div class="right-divblock">
          <h1 class="heading">Log In</h1>
          <div class="form-block login w-form">
            <form id="email-form" name="email-form" method="post" class="form">
              <div class="logindiv">
                  <input type="email" class="text-field login-texfield email-textfield w-input" maxlength="256" name="email" placeholder="Email" id="email-3" >
                  <input type="password" class="text-field login-texfield w-input" maxlength="256" name="password" placeholder="Password" id="password" >
                <a href="#" class="link-2">Forgot Password?</a>
              </div>
                <input type="submit" name="login" value="Log In" data-wait="Please wait..." class="submit-button ghost-btn w-button">
                <input type="submit" name="logout" value="Logout" data-wait="Please wait..." class="submit-button ghost-btn w-button">
              <div class="register-text-div"><label class="field-label-2">Doesn&#x27;t Have Account? </label>
                <a href="register.php" class="register-link-text">Register</a>
              </div>
            </form>
              <?php //echo 'You are '.$view->loggedin ?>
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form.</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>-->


<!-- an if statement where user will be able to log in but in this specific statement the message
 will be shown to the user that the login was successful-->

<?php

if(isset($_SESSION["loggedin"]))
    {
        echo '
    <div class="form-container" >
        <div class="section login-section" >
            <div class="login-divblock" >
                <div class="left-divblock" ></div >
                <div class="right-divblock" >
                <h1 class="heading" > Welcome! Your have successfully logged in </h1 >
                    <div class="form-block login w-form" >
                                            <form id = "email-form" name = "email-form" data - name = "Email Form" class="form" >
                                            <input type="submit" name="logout" value="Logout" data-wait="Please wait..." class="submit-button ghost-btn w-button">

                            </form>

                        </div >
                </div >
            </div >
        </div >
    </div >';

    }
// an else if statement where if user forget the password then it can rest it through clicking that button.

else {

    if(isset($_POST["forgot"]))
    {
        echo'<div class="form-container" >
        <div class="section login-section" >
            <div class="login-divblock" >
                <div class="left-divblock" ></div >
                <div class="right-divblock" >
                <h1 class="heading" > A password reset code has been sent to your email</h1 >
                    <div class="form-block login w-form" >
                            <form id = "email-form" name = "email-form" data - name = "Email Form" class="form" >
                            
                                <input type="text" class="text-field login-texfield w-input" maxlength="256" name="reset-code"  placeholder="Password Reset Code" id="address-2" required="">

                                <input type="password" class="text-field login-texfield w-input" maxlength="256" name="passwordR1" placeholder="Password" id="password" required="">
                                <input type="password" class="text-field login-texfield w-input" maxlength="256" name="passwordR2"  placeholder="Confirm Password" id="confirm-password" required="">

                                <input type="submit" name="change" value="Change Password" data-wait="Please wait..." class="submit-button ghost-btn w-button">

                            </form>';

         echo '<div class="error-message" ><div class="text-block">'.$view->resetError.'</div></div>
                        </div >
                </div >
            </div >
        </div >
    </div >';

    }

// else statement here where user needs to enter the details of the login and a link to register if user haven't registered it yet

    else {

        echo '
    <body class="login-body" >

    <div class="form-container" >
        <div class="section login-section" >
            <div class="login-divblock" >
                <div class="left-divblock" ></div >
                <div class="right-divblock" >
                    <h1 class="heading" > Log In </h1 >
                    <div class="form-block login w-form" >
                        <form id = "email-form" name = "email-form" data - name = "Email Form" class="form" >
                            <div class="logindiv" >
                                <input type = "email" class="text-field login-texfield email-textfield w-input" maxlength = "256" name = "email" placeholder = "Email" id = "email-3" required = "" >
                                <input type = "password" class="text-field login-texfield w-input" maxlength = "256" name = "password" placeholder = "Password" id = "password" >
                            </div >
                                <input type = "submit" name = "login" value = "Log In" data - wait = "Please wait..." class="submit-button ghost-btn w-button" >
                                <input type = "submit" name = "forgot" value = "Forgot Password?" data - wait = "Please wait..." class="link-2" id = "forgot-button">

                            <div class="register-text-div" >
                                <label class="field-label-2" > Doesn &#x27;t Have Account? </label>
                                <a href = "register.php" class="register-link-text" > Register</a >
                            </div >
                            <div>
                                <div class="text-block">' . $view->loggedin . '</div>
                            </div>
                        </form >
                        
                    </div >
                </div >
            </div >
        </div >
    </div >';
    }
}

?>

<!-- a footer for a website taken from the footer.phtml page of the project-->
<?php require('template/footer.phtml') ?>