<?php require('template/header.phtml') ?>

<div data-collapse="none" data-animation="default" data-duration="400" role="banner" class="navbar w-nav">
    <div class="container w-container">
        <nav role="navigation" class="w-nav-menu">
            <a href="index.php" class="nav-link nav-button w-nav-link">Home</a>
            <a href="login.php" class="nav-link nav-button w-nav-link">Log In</a>
        </nav>
        <div class="w-nav-button">
            <div class="w-icon-nav-menu"></div>
        </div>
        <a href="index.html" class="w-inline-block"><img src="../images/krm..svg" alt="" class="image"></a>
    </div>
</div>


<?php

if(isset($_SESSION["registered"]))
{
    echo'
    <div class="w-form-done">
                        <div>Thank you! You have successfully registered!</div>
                      </div>';
}

else
{
    echo'
    <div class="w-form-fail">
                    <div>Oops! Something went wrong while submitting the form.</div>
                  </div>';
}

?>
<h1>thanks for registering</h1>




<?php require('template/footer.phtml') ?>
