<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

<body class="body-3">
  <div class="form-container">
    <div class="section login-section">
      <div class="login-divblock">
        <div class="left-divblock"><img src="../images/login-image.jpg" srcset="../images/login-image-p-500.jpeg 500w, images/login-image-p-800.jpeg 800w, images/login-image-p-1080.jpeg 1080w, images/login-image-p-1600.jpeg 1600w, images/login-image-p-2000.jpeg 2000w, images/login-image-p-2600.jpeg 2600w, images/login-image-p-3200.jpeg 3200w, images/login-image.jpg 6622w" sizes="(max-width: 767px) 100vw, (max-width: 991px) 46vw, 100vw" alt="" class="image-3"></div>
        <div class="right-divblock">
          <h1 class="headingr">Register</h1>
          <div class="form-block login w-form">
            <form id="email-form" name="email-form" method="post" class="form">

                  <input type="text" class="text-field login-texfield w-input"  name="name" placeholder="Full Name" required="">
                  <input type="email" class="text-field login-texfield w-input"  name="email" data-name="Email" placeholder="Email" id="email" required="">
                  <input type="number" class="text-field login-texfield w-input" name="number" placeholder="Phone Number" required="">
                  <input type="text" class="text-field login-texfield w-input"  name="address1" placeholder="Address Line 1" required="">
                  <input type="text" class="text-field login-texfield w-input"  name="address2" placeholder="Address Line 2" required="">
                  <input type="text" class="text-field login-texfield w-input" name="postcode" placeholder="Post/Zip Code" required="">
                  <input type="password" class="text-field login-texfield w-input"  name="password1" placeholder="Password" required="">
                  <input type="password" class="text-field login-texfield w-input"  name="password2" placeholder="Confirm Password" id="confirm-password" required="">

                <input type="submit" name="register" value="Register" class="submit-button ghost-btn w-button">

              <div class="register-text-div">
                  <label class="field-label-2">Already have an account?</label>
                <a href="login.php" class="register-link-text">Log In</a>
              </div>
            </form>

              <?php

              echo $view->register;

              if(isset($_SESSION["registered"]))
              {
                  echo'
    <div class="w-form-done">
                        <div>Thank you! You have successfully registered!</div>
                      </div>';
              }

              else
              {
                  echo'
    <div class="w-form-fail">
                    <div>Oops! Something went wrong while submitting the form.</div>
                  </div>';
              }

              ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<?php require('template/footer.phtml') ?>