    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <div class="footer-container"><img src="images/Screenshot-2021-01-13-at-00.21.32.png" loading="lazy" sizes="(max-width: 3360px) 100vw, 3360px" srcset="images/Screenshot-2021-01-13-at-00.21.32-p-500.png 500w, images/Screenshot-2021-01-13-at-00.21.32-p-800.png 800w, images/Screenshot-2021-01-13-at-00.21.32-p-1080.png 1080w, images/Screenshot-2021-01-13-at-00.21.32-p-1600.png 1600w, images/Screenshot-2021-01-13-at-00.21.32-p-2000.png 2000w, images/Screenshot-2021-01-13-at-00.21.32-p-2600.png 2600w, images/Screenshot-2021-01-13-at-00.21.32-p-3200.png 3200w, images/Screenshot-2021-01-13-at-00.21.32.png 3360w" alt=""></div>
            <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ffdee642c9118659a48a86b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
            <script src="js/webflow.js" type="text/javascript"></script>
            <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->


            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ffdee642c9118659a48a86b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="js/webflow.js" type="text/javascript"></script>
    <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
    </body>