</div>


<div class="matt-fard"></div>
    <footer id="footer" class="footer">
        <div class="container-2 w-container">
            <div class="footer-flex-container-2">
                <a href="index.php" class="footer-logo-link w-inline-block"><img src="images/krm._1.svg" alt="" class="footer-image"></a>
                <div class="div-block-16">
                    <h2 class="footer-heading">KRM B. V.</h2>
                    <div class="text-block-5">Marineweg 3a<br>2241 TX Wassenaar</div>
                    <ul role="list" class="list w-list-unstyled">
                        <li>
                            <a href="tel:0702060100" class="footer-link footer-dontact">070-2060100</a>
                        </li>
                    </ul>
                    <a href="https://krm.nl/iso-9001-2015/" target="_blank" class="w-inline-block"><img src="images/isocertbutton60.png" loading="lazy" alt=""></a>
                </div>
                <div class="div-block-15">
                    <h2 class="footer-heading">Actualiteit | Blogs | Nieuws</h2>
                    <ul role="list" class="w-list-unstyled">
                        <li>
                            <a href="https://krm.nl/intervisie/" class="footer-link">Intervisie</a>
                        </li>
                        <li>
                            <a href="https://krm.nl/cybercrime/" class="footer-link">Cybercrime</a>
                        </li>
                    </ul>
                    <a href="https://krm.nl/is-plan-om-goudvis-verslaan/" class="footer-link">Wat is jouw plan om de goudvis te verslaan?</a>
                    <a href="https://krm.nl/is-why-architecten-kpn-zm-bo/" class="footer-link">Wat is de ‘WHY’ van de architecten van KPN ZM BO</a>
                </div>
                <div class="div-block-17">
                    <h2 class="footer-heading">Snel menu</h2>
                    <ul role="list" class="w-list-unstyled">
                        <li>
                            <a href="https://krm.nl/actuele-vacatures/" class="footer-link">Actuele Vacatures</a>
                        </li>
                        <li>
                            <a href="https://krm.nl/open-sollicitatie/" class="footer-link">Open sollicitatie</a>
                        </li>
                        <li>
                            <a href="https://krm.nl/het-krm-team/" class="footer-link">Het KRM team</a>
                        </li>
                    </ul>
                    <a href="https://krm.nl/category/blog-column/" class="footer-link">Actualiteiten | Blog | Nieuws</a>
                    <a href="https://krm.nl/contact/" class="footer-link">Contact</a>
                </div>
            </div>
            <div class="text-block-4">Copyright KRM 2018 - <a href="https://krm.nl/privacy/" target="_blank" class="link-4">Privacy Statement</a> - Proudly Powered by <a href="https://www.sebassahmedia.nl/" target="_blank" class="link-3">Sebassah Media</a>
            </div>
        </div>
    </footer>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ffdee642c9118659a48a86b" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="js/webflow.js" type="text/javascript"></script>
    <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
    </body>