<!DOCTYPE html>
<html lang="en" page="60005b299b49ba8486db6c9c"  data-wf-site="5ffdee642c9118659a48a86b">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">
    <!DOCTYPE html><!--  This site was created in Webflow. http://www.webflow.com  -->
    <!--  Last Published: Wed Jan 13 2021 11:12:18 GMT+0000 (Coordinated Universal Time)  -->

    <meta charset="utf-8">
    <title>home</title>
    <meta content="home" property="og:title">
    <meta content="home" property="twitter:title">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
    <link href="css/normalize.css" rel="stylesheet" type="text/css">
    <link href="css/webflow.css" rel="stylesheet" type="text/css">
    <link href="css/krm-5b821e.webflow.css" rel="stylesheet" type="text/css">
    <script src="js/webflow.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">WebFont.load({  google: {    families: ["Roboto:100,300,regular,500,700,900","Roboto Condensed:300,regular"]  }});</script>
    <!-- [if lt IE 9]><script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
    <link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="images/webclip.png" rel="apple-touch-icon">
</head>

<body role=""document">

<?php
$login = "Log In";
$name = null;

if(isset($_SESSION["loggedin"]))
{
    $login = "Log Out";
    $name = $_SESSION["na"];
}

?>

<div class="container">
    <div data-collapse="small" data-animation="default" data-duration="400" role="banner" class="navbar-2 w-nav">
        <div class="w-container">
            <a href="index.php" aria-current="page" class="w-nav-brand w--current"><img src="images/krm..svg" loading="lazy" alt="" class="image-4"></a>
            <nav role="navigation" class="nav-menu w-nav-menu">
                <a href="form.php" class="nav-link-3 w-nav-link">New Application</a>
                <a href="history.php" class="nav-link-3 w-nav-link">History</a>
                <a href="contact.php" class="nav-link-3 w-nav-link">Contact Us</a>
                <a href="login.php" class="nav-link-2 nav-link w-nav-link"><?php echo $login; ?></a>
                <a href="profile.php" class="nav-link-3 w-nav-link"><?php echo $name; ?></a>
            </nav>
            <div class="menu-button w-nav-button">
                <div class="icon w-icon-nav-menu"></div>
            </div>
        </div>
    </div>

    <!--<nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="form.php">Project Application</a></li>
            <li><a href="login.php">Login</a></li>

        </ul>
    </nav>-->



    <!--<div id="content" >-->



